name: pre-release

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.x
          8.x
    - name: Get the version
      id: get_version
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: './Directory.Build.props'
        xpath: '//Version'
    - name: Create short version
      id: shortversion
      run: |
        $version = "${{ steps.get_version.outputs.info }}".Substring(0, "${{ steps.get_version.outputs.info }}".LastIndexOf("."))
        Write-Host "::set-output name=shortversion::$version-alpha"
      shell: pwsh
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release -p:VersionSuffix=alpha ./SerilogSinksInMemory.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
    - name: Create NuGet package for Serilog.Sinks.InMemory
      run: dotnet pack ./src/Serilog.Sinks.InMemory/Serilog.Sinks.InMemory.csproj -c Release --no-build --no-restore -o ./packaging -p:VersionSuffix=alpha
    - name: Create NuGet package for Serilog.Sinks.InMemory.Assertions
      run: dotnet pack ./src/Serilog.Sinks.InMemory.Assertions/Serilog.Sinks.InMemory.Assertions.csproj -c Release --no-build --no-restore -o ./packaging -p:VersionSuffix=alpha
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.info }}-alpha
        release_name: ${{ steps.get_version.outputs.info }}-alpha
        draft: false
        prerelease: true
    - name: Upload sink NuGet package
      id: upload-nuget-sink
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./packaging/Serilog.Sinks.InMemory.${{ steps.shortversion.outputs.shortversion }}.nupkg
        asset_name: Serilog.Sinks.InMemory.${{ steps.shortversion.outputs.shortversion }}.nupkg
        asset_content_type: application/octet-stream
    - name: Upload assertions NuGet package
      id: upload-nuget-assertions
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./packaging/Serilog.Sinks.InMemory.Assertions.${{ steps.shortversion.outputs.shortversion }}.nupkg
        asset_name: Serilog.Sinks.InMemory.Assertions.${{ steps.shortversion.outputs.shortversion }}.nupkg
        asset_content_type: application/octet-stream
